# Generated by Django 3.0 on 2021-12-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
    ]
