# Generated by Django 3.0 on 2021-12-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_auto_20211222_1235'),
    ]

    operations = [
    ]
