# Generated by Django 3.0 on 2021-12-22 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_auto_20211222_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
