# Generated by Django 4.0.2 on 2022-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0004_auto_20211222_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
